server:
  port: 8081

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/v2

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: INFO

spring:
  application:
    name: webapp-service

---
spring:
  profiles: eureka-embedded

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/
