server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/v2/

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: WARN

spring:
  application:
    name: webapp-service

log4j:
  category:
    org.springframework: WARN
  level:
    com.netflix.discovery: DEBUG
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: WARN
    