server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/v2/


logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: WARN

spring:
  application:
    name: webapp-service

log4j:
  category:
    org.springframework: DEBUG
  level:
    com.netflix.discovery: DEBUG
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: WARN
    