server:
  port: 8087

storage:
  backend: file-storage
  directory: /tmp/files

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/

ribbon:
  ServerListRefreshInterval: 5000

spring:
  application:
    name: files-service

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF