#/bin/bash

export SPRING_REDIS_SENTINEL_MASTER="mymaster"
echo "SPRING_REDIS_SENTINEL_MASTER: ${SPRING_REDIS_SENTINEL_MASTER}"
export SPRING_REDIS_SENTINEL_NODES=${REDIS_SENTINEL_SERVICE_HOST}:${REDIS_SENTINEL_SERVICE_PORT}
echo "SPRING_REDIS_SENTINEL_NODES: ${SPRING_REDIS_SENTINEL_NODES}"
