{{K8S_DNS_HOST=$(echo $DOCKER_HOST | awk -F'[/:]' '{print $4}')}}
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-dns
  namespace: kube-system
subsets:
- addresses:
  - ip: {{K8S_DNS_HOST}}
  ports:
  - port: 53
    protocol: UDP
    name: dns
