kind: ReplicationController
apiVersion: v1beta2
id: kube-dns
namespace: default
labels:
  k8s-app: kube-dns
  kubernetes.io/cluster-service: "true"
desiredState:
  replicas: 1
  replicaSelector:
    k8s-app: kube-dns
  podTemplate:
    labels:
      name: kube-dns
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
    desiredState:
      manifest:
        version: v1beta2
        id: kube-dns
        dnsPolicy: "Default"  # Don't use cluster DNS.
        containers:
          - name: etcd
            image: quay.io/coreos/etcd:v2.0.3
            command: [
                    "-listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001",
                    "-initial-cluster-token=skydns-etcd",
                    "-advertise-client-urls=http://127.0.0.1:4001"
            ]
          - name: kube2sky
            image: gcr.io/google_containers/kube2sky:1.2
            command: [
                    "-etcd-server=http://127.0.0.1:4001",
                    "-domain=riox.internal"
            ]
          - name: skydns
            image: gcr.io/google_containers/skydns:2015-03-11-001
            command: [
                    "-machines=http://127.0.0.1:4001",
                    "-addr=0.0.0.0:53",
                    "-domain=riox.internal",
                    "-nameservers=8.8.8.8:53,8.8.4.4:53"
            ]
            ports:
              - name: dns
                containerPort: 53
                protocol: UDP
