kind: ReplicationController
apiVersion: v1beta2
id: xd-admin
labels:
  name: xd-admin
desiredState:
  replicas: 1
  replicaSelector:
    name: xd-admin
  podTemplate:
    labels:
      name: xd-admin
    desiredState:
      manifest:
        version: v1beta2
        id: xd-admin
        containers:
          - name: xd-admin
            image: riox/springxd-admin:1.1.2
            ports: 
              - containerPort: 9393
