apiVersion: v1
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: gateway
      labels:
        name: gateway
    spec:
      replicas: 1
      selector:
        name: gateway
      template:
        metadata:
          labels:
            name: gateway
        spec:
          imagePullSecrets:
            - name: rioxregistrykey
          containers:
            - name: gateway
              image: riox/hyperriox:472c4d85d58795b459ed9fc698be76d2aa483955
              ports:
                - containerPort: 80
              command:
                  - "gulp"
                  - "gateway:start"
              env:
                - name: RIOX_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace

  - kind: Service
    apiVersion: v1
    metadata:
      name: gateway
    spec:
      ports:
        - port: 80
      type: LoadBalancer
      selector:
        name: gateway
