server:
  port: 8086

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://eureka.riots.io:10000/eureka/v2/
  instance:
    leaseRenewalIntervalInSeconds: 10

ribbon:
  ServerListRefreshInterval: 5000

spring:
  application:
    name: simulation-service

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF