server:
  port: 8086

mongodb:
  hostname: localhost

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/v2

activemq:
  hostname: localhost
  brokerURL: tcp://${activemq.hostname}:61616

ribbon:
  ServerListRefreshInterval: 5000

spring:
  application:
    name: simulation-service

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF

---
spring:
  profiles: eureka-embedded

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/
