server:
  port: 8087

spring:
  application:
    name: files-service

endpoints:
  health:
    sensitive: false

storage:
  backend: fileStorage
  directory: /var/tmp/riots-file-service-data

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/

ribbon:
  ServerListRefreshInterval: 5000

logging:
  level:
    org.apache.cxf: OFF
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF
