apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    name: elasticsearch
  template:
    metadata:
      labels:
         name: elasticsearch
    spec:
      imagePullSecrets:
        - name: rioxregistrykey
      containers:
      - name: elasticsearch
        image: riox/elasticsearch
        env:
          - name: "CLUSTER_NAME"
            value: "elasticsearch"
          - name: "SELECTOR"
            value: "name=elasticsearch"
        ports:
        - name: es
          containerPort: 9200
        - name: es-transport
          containerPort: 9300
