apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  selector:
    name: elasticsearch
  ports:
  - name: db
    port: 9200
    targetPort: es
    nodePort: 0
  - name: db-transport
    port: 9300
    targetPort: es-transport
    nodePort: 0
