apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  selector:
    name: elasticsearch
  ports:
  - name: db
    port: 9200
    targetPort: es
  type: LoadBalancer
