apiVersion: v1
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: riox-ui
      labels:
        name: riox-ui
    spec:
      replicas: 2
      selector:
        name: riox-ui
      template:
        metadata:
          labels:
            name: riox-ui
        spec:
          imagePullSecrets:
            - name: rioxregistrykey
          containers:
            - name: riox-ui
              image: riox/hyperriox:472c4d85d58795b459ed9fc698be76d2aa483955
              ports:
                - containerPort: 8081
              command:
                - "gulp"
                - "ui:serve:prod"
              env:
                - name: RIOX_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8081
                initialDelaySeconds: 15
                timeoutSeconds: 1
  - kind: Service
    apiVersion: v1
    metadata:
      name: riox-ui
    spec:
      ports:
        - port: 8081
      selector:
        name: riox-ui
