apiVersion: v1
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: analytics-service
      labels:
        name: analytics-service
    spec:
      replicas: 2
      selector:
        name: analytics-service
      template:
        metadata:
          labels:
            name: analytics-service
        spec:
          imagePullSecrets:
            - name: rioxregistrykey
          containers:
            - name: analytics-service
              image: riox/hyperriox:472c4d85d58795b459ed9fc698be76d2aa483955
              ports:
                - containerPort: 8086
              command:
                - "gulp"
                - "services:analytics:serve"
              env:
                - name: RIOX_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8086
                initialDelaySeconds: 5
                timeoutSeconds: 1


  - kind: Service
    apiVersion: v1
    metadata:
      name: analytics-service
    spec:
      ports:
        - port: 8086
      selector:
        name: analytics-service
