files:
  image: 146.148.126.222:5000/riots/service-files
  volumes:
    - /data/files:/data
  ports: 
    - "8087:8087"
  environment:
    JAVA_OPTS: "-Deureka.hostname=10.240.227.116 -Dstorage.directory=/data"

catalog:
  image: 146.148.126.222:5000/riots/service-catalog
  ports:
    - "8083:8083"
  links:
    - files
  environment:
    JAVA_OPTS: "-Deureka.hostname=10.240.227.116 -Delasticsearch.hostname=10.240.227.116"

environment:
  image: 146.148.126.222:5000/riots/service-environment
  ports:
    - "8085:8085"
  environment:
    JAVA_OPTS: "-Deureka.hostname=10.240.227.116 -Dmongodb.hostname=10.240.227.116 -Dactivemq.hostname=10.240.227.116"

simulation:
  image: 146.148.126.222:5000/riots/service-simulation
  ports:
    - "8086:8086"
  environment:
    JAVA_OPTS: "-Deureka.hostname=10.240.227.116 -Dmongodb.hostname=10.240.227.116 -Dactivemq.hostname=10.240.227.116"

users:
  image: 146.148.126.222:5000/riots/service-users
  ports:
    - "8084:8084"
  environment:
    JAVA_OPTS: "-Deureka.hostname=10.240.227.116 -Dmongodb.hostname=10.240.227.116"

gateway:
  image: 146.148.126.222:5000/riots/service-gateway
  ports:
    - "8080:8080"
  environment:
    JAVA_OPTS: "-Deureka.hostname=10.240.227.116"

webapp: 
  image: 146.148.126.222:5000/riots/webapp
  ports:
    - "8081:8081"
  environment:
    JAVA_OPTS: "-Deureka.hostname=10.240.227.116"
