server:
  port: 8085
  
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/v2/
  instance:
    leaseRenewalIntervalInSeconds: 10

ribbon:
  ServerListRefreshInterval: 5000

spring:
  application:
    name: environment-service

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF