apiVersion: v1
kind: List
items:
  - kind: Service
    metadata:
      name: gateway
      labels:
        name: gateway
    spec:
      selector:
        name: gateway
      ports:
      - name: http
        port: 80
        targetPort: http
      - name: https
        port: 443
        targetPort: https
      type: LoadBalancer

  - kind: Service
    metadata:
      name: nginx-config
      labels:
        name: nginx-config
    spec:
      selector:
        name: gateway
      ports:
      - name: api
        port: 8082
        targetPort: api
