
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "zookeeper-2",
    "labels": {
      "name": "zookeeper",
      "server-id": "2"
    }
  },
  "spec": {
    "containers": [
      {
        "name": "server",
        "image": "fabric8/zookeeper",
        "env":[
          { "name": "SERVER_ID", "value": "2" },
          { "name": "MAX_SERVERS", "value": "3" }
        ],
        "ports":[
          {
            "containerPort": 2181
          },
          {
            "containerPort": 2888
          },
          {
            "containerPort": 3888
          }
        ]
      }
    ]
  }
}
