{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "zookeeper-3",
    "labels": {
      "name": "zookeeper-3"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "client",
        "port": 2181,
        "targetPort": 2181
      },
      {
        "name": "followers",
        "port": 2888,
        "targetPort": 2888
      },
      {
        "name": "election",
        "port": 3888,
        "targetPort": 3888
      }
    ],
    "selector": {
      "server-id": "3"
    }
  }
}
