kind: ReplicationController
apiVersion: v1
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  replicas: 1
  selector:
    name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: server
          #image: mbabineau/zookeeper-exhibitor
          image: riox/zookeeper-exhibitor:3.4.6
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
            - containerPort: 8181
