kind: ReplicationController
apiVersion: v1
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  replicas: 1
  selector:
    name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: server
          image: mbabineau/zookeeper-exhibitor
          env:
            - name: S3_BUCKET
              value: riox-zookeeper
            - name: S3_PREFIX
              value: riox
            - name: AWS_REGION
              value: eu-central-1
            - name: AWS_ACCESS_KEY_ID
              value: AKIAJTG2CN2AXVU2ULQQ
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: HOSTNAME
              value: zookeeper.dev.svc.cluser.internal
          # env:
          #   - name: SERVER_ID
          #     value: "1"
          #   - name: MAX_SERVERS
          #     value: "1"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
            - containerPort: 8181
