#/bin/bash

export MYSQL_DATABASE="springxd"
export MYSQL_USER="riox"
export MYSQL_PASSWORD="rioxRocks2015!"

export SPRING_DATASOURCE_URL="jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/${MYSQL_DATABASE}"
echo "SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}"
export SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
echo "SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}"
export SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
echo "SPRING_DATASOURCE_PASSWORD: ***********"
export SPRING_DATASOURCE_DRIVERCLASSNAME="com.mysql.jdbc.Driver"
export SPRING_DATASOURCE_VALIDATIONQUERY="select 1"

export ZK_CLIENT_CONNECT=$ZOOKEEPER_SERVICE_HOST:$ZOOKEEPER_SERVICE_PORT_CLIENT
echo "ZK_CLIENT_CONNECT: ${ZK_CLIENT_CONNECT}"

export SPRING_REDIS_SENTINEL_MASTER="mymaster"
echo "SPRING_REDIS_SENTINEL_MASTER: ${SPRING_REDIS_SENTINEL_MASTER}"
export SPRING_REDIS_SENTINEL_NODES=${REDIS_SENTINEL_SERVICE_HOST}:${REDIS_SENTINEL_SERVICE_PORT}
echo "SPRING_REDIS_SENTINEL_NODES: ${SPRING_REDIS_SENTINEL_NODES}"

export XD_TRANSPORT=kafka
export XD_MESSAGEBUS_KAFKA_BROKERS=${KAFKA_SERVICE_HOST}:${KAFKA_SERVICE_PORT}
echo "XD_MESSAGEBUS_KAFKA_BROKERS: ${XD_MESSAGEBUS_KAFKA_BROKERS}"

export XD_MESSAGEBUS_KAFKA_ZKADDRESS=$ZOOKEEPER_SERVICE_HOST:$ZOOKEEPER_SERVICE_PORT_CLIENT
echo "XD_MESSAGEBUS_KAFKA_ZKADDRESS: ${XD_MESSAGEBUS_KAFKA_ZKADDRESS}"

# Does not seem to support hot deployment
#export XD_CUSTOMMODULE_HOME=file:///opt/spring-xd/riox-modules
#echo "XD_CUSTOMMODULE_HOME: ${XD_CUSTOMMODULE_HOME}"
