package io.riots.core.sim;

import io.riots.core.model.PropertyValue;
import io.riots.core.model.sim.SimulationRun;

/**
 * Listener to process updates generated by a running simulation.
 * @author whummer
 */
public interface SimulationListener {

	void updateValue(SimulationRun sim, PropertyValue<?> value);

}
