{{IMAGE_VERSION=latest}}
{{PULL_POLICY=Always}}
{{BASE_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )}}
apiVersion: v1
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: users-service
      labels:
        name: users-service
    spec:
      replicas: 2
      selector:
        name: users-service
      template:
        metadata:
          labels:
            name: users-service
        spec:
          imagePullSecrets:
            - name: rioxregistrykey
          containers:
            - name: users-service
              image: riox/hyperriox:{{IMAGE_VERSION}}
              imagePullPolicy: {{PULL_POLICY}}
              ports:
                - containerPort: 8084
              command:
                - "gulp"
                - "services:users:run"
              env:
                - name: RIOX_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8084
                initialDelaySeconds: 60
                timeoutSeconds: 3
              {{MOUNT_LOCAL_CMD}}volumeMounts:
                {{MOUNT_LOCAL_CMD}}- mountPath: "/code"
                  {{MOUNT_LOCAL_CMD}}name: "riox-code-dir"
          {{MOUNT_LOCAL_CMD}}volumes:
            {{MOUNT_LOCAL_CMD}}- hostPath:
                {{MOUNT_LOCAL_CMD}}path: {{BASE_PATH}}
              {{MOUNT_LOCAL_CMD}}name: riox-code-dir

  - kind: Service
    apiVersion: v1
    metadata:
      name: users-service
    spec:
      ports:
        - port: 8084
      selector:
        name: users-service

  - kind: Service
    apiVersion: v1
    metadata:
      name: certificates-service
    spec:
      ports:
        - port: 8084
      selector:
        name: users-service

  - kind: Service
    apiVersion: v1
    metadata:
      name: notifications-service
    spec:
      ports:
        - port: 8084
      selector:
        name: users-service

  - kind: Service
    apiVersion: v1
    metadata:
      name: organizations-service
    spec:
      ports:
        - port: 8084
      selector:
        name: users-service
