package io.riots.core.sim;

import io.riots.services.scenario.PropertyValue;
import io.riots.services.sim.SimulationRun;

/**
 * Listener to process updates generated by a running simulation.
 * @author whummer
 */
public interface SimulationListener {

	void updateValue(SimulationRun sim, PropertyValue value);

}
