server:
  port: 10000

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/v2
  server:
    waitTimeInMsWhenSyncEmpty: 0


logging:
  level:
    com.netflix.discovery: 'TRACE'
    org.apache.http: 'TRACE'
    org.springframework: 'WARN'

---
spring:
  profiles: eureka-embedded

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/
