server:
  port: 10000

spring:
  application:
    name: riots-registry

endpoints:
  health:
    sensitive: false

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0


logging:
  level:
    com.netflix.discovery: 'TRACE'
    org.apache.http: 'TRACE'
    org.springframework: 'WARN'
