server:
  port: 10000

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5

  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix.discovery: TRACE
    org.apache.http: TRACE
    org.springframework: WARN

