server:
  port: 8084

mongodb:
  hostname: localhost	

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/

spring:
  application:
    name: users-service

endpoints:
    health:
      sensitive: false

logging:
  level:
    com.netflix.discovery: INFO
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: WARN