server:
  port: 8084

spring:
  application:
    name: users-service

mongodb:
  hostname: localhost	

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/

endpoints:
    health:
      sensitive: false

logging:
  level:
    com.netflix.discovery: INFO
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework: TRACE