server:
  port: 8084

mongodb:
  hostname: localhost	

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/v2/

spring:
  application:
    name: users-service

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: WARN
