{{IMAGE_VERSION=latest}}
apiVersion: v1
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: streams-service
      labels:
        name: streams-service
    spec:
      replicas: 2
      selector:
        name: streams-service
      template:
        metadata:
          labels:
            name: streams-service
        spec:
          imagePullSecrets:
            - name: rioxregistrykey
          containers:
            - name: streams-service
              image: riox/hyperriox:{{IMAGE_VERSION}}
              ports:
                - containerPort: 8085
              command:
                - "gulp"
                - "services:streams:run"
              env:
                - name: RIOX_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8085
                initialDelaySeconds: 60
                timeoutSeconds: 3

  - kind: Service
    apiVersion: v1
    metadata:
      name: streams-service
    spec:
      ports:
        - port: 8085
      selector:
        name: streams-service

  - kind: Service
    apiVersion: v1
    metadata:
      name: access-service
    spec:
      ports:
        - port: 8085
      selector:
        name: streams-service

  - kind: Service
    apiVersion: v1
    metadata:
      name: gateway-service
    spec:
      ports:
        - port: 8085
      selector:
        name: streams-service
  - kind: Service
    apiVersion: v1
    metadata:
      name: ratings-service
    spec:
      ports:
        - port: 8085
      selector:
        name: streams-service
  - kind: Service
    apiVersion: v1
    metadata:
      name: statistics-service
    spec:
      ports:
        - port: 8085
      selector:
        name: streams-service
  - kind: Service
    apiVersion: v1
    metadata:
      name: consents-service
    spec:
      ports:
        - port: 8085
      selector:
        name: streams-service
