apiVersion: v1beta3
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1beta2
    id: streams-service
    labels:
      name: streams-service
    desiredState:
      replicas: 1
      replicaSelector:
        name: streams-service
      podTemplate:
        labels:
          name: streams-service
        desiredState:
          manifest:
            version: v1beta2
            id: streams-service
            containers:
              - name: streams-service
                image: riox/codebase
                ports:
                  - containerPort: 8085
                command: [
                    "gulp",
                    "services:streams:serve"
                ]
  - kind: Service
    apiVersion: v1beta2
    id: streams-service
    port: 8085
    containerPort: 8085
    selector:
      name: streams-service
  - kind: Service
    apiVersion: v1beta2
    id: access-service
    port: 8085
    containerPort: 8085
    selector:
      name: streams-service
  - kind: Service
    apiVersion: v1beta2
    id: gateway-service
    port: 8085
    containerPort: 8085
    selector:
      name: streams-service
  - kind: Service
    apiVersion: v1beta2
    id: ratings-service
    port: 8085
    containerPort: 8085
    selector:
      name: streams-service
  - kind: Service
    apiVersion: v1beta2
    id: statistics-service
    port: 8085
    containerPort: 8085
    selector:
      name: streams-service
  - kind: Service
    apiVersion: v1beta2
    id: consents-service
    port: 8085
    containerPort: 8085
    selector:
      name: streams-service
      