{{IMAGE_VERSION=latest}}
{{PULL_POLICY=Always}}
{{BASE_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )}}
apiVersion: v1
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: analytics-service
      labels:
        name: analytics-service
    spec:
      replicas: 2
      selector:
        name: analytics-service
      template:
        metadata:
          labels:
            name: analytics-service
        spec:
          imagePullSecrets:
            - name: rioxregistrykey
          containers:
            - name: analytics-service
              image: riox/hyperriox:{{IMAGE_VERSION}}
              imagePullPolicy: {{PULL_POLICY}}
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "50m"
                limits:
                  memory: "350Mi"
                  cpu: "100m"
              ports:
                - containerPort: 8086
              command:
                - "gulp"
                - "services:analytics:run"
              env:
                - name: RIOX_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8086
                initialDelaySeconds: 30
                timeoutSeconds: 3

  - kind: Service
    apiVersion: v1
    metadata:
      name: analytics-service
    spec:
      ports:
        - port: 8086
      selector:
        name: analytics-service
