kind: ReplicationController
apiVersion: v1
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  replicas: 1
  selector:
    name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
          - name: kafka
            image: riox/kafka
            env:
              - name: KAFKA_ZOOKEEPER_CONNECT
                value: zookeeper-1.production.svc.cluster.local:2181,zookeeper-2.production.svc.cluster.local:2181,zookeeper-3.production.svc.cluster.local:2181
            ports:
              - containerPort: 9092
