kind: ReplicationController
apiVersion: v1
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  replicas: 1
  selector:
    name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
          - name: kafka
            image: riox/kafka:0.8.2.2
            env:
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            ports:
              - containerPort: 9092
