{{IMAGE_VERSION=latest}}
{{PULL_POLICY=Always}}
{{BASE_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )}}
apiVersion: v1
kind: List
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: riox-ui
      labels:
        name: riox-ui
    spec:
      replicas: 2
      selector:
        name: riox-ui
      template:
        metadata:
          labels:
            name: riox-ui
        spec:
          imagePullSecrets:
            - name: rioxregistrykey
          containers:
            - name: riox-ui
              image: riox/hyperriox:{{IMAGE_VERSION}}
              imagePullPolicy: {{PULL_POLICY}}
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "50m"
                limits:
                  memory: "512Mi"
                  cpu: "100m"
              ports:
                - containerPort: 8081
              command:
                - "gulp"
                - "ui:serve:prod"
              env:
                - name: RIOX_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8081
                initialDelaySeconds: 60
                timeoutSeconds: 3

  - kind: Service
    apiVersion: v1
    metadata:
      name: riox-ui
    spec:
      ports:
        - port: 8081
      selector:
        name: riox-ui
