server:
  port: 8082

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/v2/
  instance:
    leaseRenewalIntervalInSeconds: 5


spring:
  application:
    name: showcase-service
  profiles:
    active: native

logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.zuul: WARN
    com.netflix.servo: WARN
    org.springframework.boot: WARN
