kind: ReplicationController
apiVersion: v1
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  replicas: 1
  selector:
    name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      imagePullSecrets:
        - name: rioxregistrykey
      containers:
          - name: mongo
            image: mongo
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "250m"
            args: ["--smallfiles"]
            ports:
              - containerPort: 27017
#            volumeMounts:
#              - name: mongo-db-mount
#                mountPath: /data/mongo/db
#      volumes:
#        - name: mongo-db-mount
