kind: ReplicationController
apiVersion: v1
metadata:
  name: mongo-3
  labels:
    name: mongo
spec:
  replicas: 1
  selector:
    name: mongo-3
  template:
    metadata:
      labels:
        name: mongo-3
    spec:
      imagePullSecrets:
        - name: rioxregistrykey
      containers:
          - name: mongo
            image: riox/mongo
            args: ["--smallfiles", "--replSet=rs0"]
            ports:
              - containerPort: 27017
    labels:
      name: mongo
#            volumeMounts:
#              - name: mongo-db-mount
#                mountPath: /data/mongo/db
#      volumes:
#        - name: mongo-db-mount
