kind: ReplicationController
apiVersion: v1
metadata:
  name: mongo-1
  labels:
    name: mongo
spec:
  replicas: 1
  selector:
    name: "mongo-1"
  template:
    metadata:
      labels:
        name: "mongo-1"
    spec:
      containers:
          - name: mongo
            image: mongo:3.0.2
            args: ["--smallfiles", "--replSet=rs0"]
            ports:
              - containerPort: 27017
    labels:
      name: mongo
#            volumeMounts:
#              - name: mongo-db-mount
#                mountPath: /data/mongo/db
#      volumes:
#        - name: mongo-db-mount
