kind: ReplicationController
apiVersion: v1
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  replicas: 3
  selector:
    name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
          - name: mongo
            image: mongo:3.0.2
            args: ["--smallfiles", "--replSet=rs0"]
            ports:
              - containerPort: 27017
#            volumeMounts:
#              - name: mongo-db-mount
#                mountPath: /data/mongo/db
#      volumes:
#        - name: mongo-db-mount
