server:
  port: 8085

spring:
  application:
    name: environment-service

endpoints:
  health:
    sensitive: false


mongodb:
  hostname: localhost

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/

activemq:
  hostname: localhost
  brokerURL: tcp://${activemq.hostname}:61616

ribbon:
  ServerListRefreshInterval: 5000

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF
    org.apache.cxf: OFF
    org.apache.cxf.interceptor: OFF
    org.apache.cxf.phase: OFF
    org.apache.cxf.jaxrs: OFF
