server:
  port: 8080

zuul:
  routes:
    api:
      path: /api/**
      stripPrefix: false
      serviceId: showcase-service
    webapp:
      path: /app/**
      stripPrefix: false
      serviceId: webapp-service
    bower:
      path: /bower_components/**
      stripPrefix: false
      serviceId: webapp-service
    websocket:
      path: /websocket
      stripPrefix: false
      serviceId: webapp-service
    favicon:
      path: /favicon.ico
      stripPrefix: false
      serviceId: webapp-service

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/v2/
  instance:
    leaseRenewalIntervalInSeconds: 10

ribbon:
  ServerListRefreshInterval: 5000
  
spring:
  application:
    name: gateway-service

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF
    com.netflix.servo: WARN
    org.springframework: DEBUG
    org.springframework.cloud.netflix.zuul: INFO
