server:
  port: 8080

zuul:
  routes:
    api-users:
      path: /api/v1/users/**
      stripPrefix: false
      serviceId: users-service
    api-ratings:
      path: /api/v1/ratings/**
      stripPrefix: false
      serviceId: users-service
    api-things:
      path: /api/v1/things/**
      stripPrefix: false
      serviceId: environment-service
    api-drivers:
      path: /api/v1/drivers/**
      stripPrefix: false
      serviceId: environment-service
    catalog-service:
      path: /api/v1/catalog/**
      stripPrefix: false

    webapp-service:
      path: /app/**
      stripPrefix: false
    bower:
      path: /bower_components/**
      stripPrefix: false
      serviceId: webapp-service
    favicon:
      path: /favicon.ico
      stripPrefix: false
      serviceId: webapp-service

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

ribbon:
  ServerListRefreshInterval: 5000
  
spring:
  application:
    name: gateway-service

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF
    com.netflix.servo: WARN
    org.springframework: WARN
    org.springframework.cloud.netflix.zuul: INFO
