server:
  port: 8080

zuul:
  routes:
    api-users:
      path: /api/v1/users/**
      stripPrefix: false
      serviceId: users-service
    api-ratings:
      path: /api/v1/ratings/**
      stripPrefix: false
      serviceId: users-service
    api-stats:
      path: /api/v1/stats/**
      stripPrefix: false
      serviceId: users-service
    api-apps:
      path: /api/v1/apps/**
      stripPrefix: false
      serviceId: environment-service
    api-things:
      path: /api/v1/things/**
      stripPrefix: false
      serviceId: environment-service
    api-utils:
      path: /api/v1/utils/**
      stripPrefix: false
      serviceId: environment-service
    api-drivers:
      path: /api/v1/drivers/**
      stripPrefix: false
      serviceId: environment-service
    catalog-service:
      path: /api/v1/catalog/**
      stripPrefix: false
    simulation-service:
      path: /api/v1/simulations/**
      stripPrefix: false

    webapp-service:
      path: /app/**
      stripPrefix: false
    webapp-bower:
      path: /bower_components/**
      stripPrefix: false
      serviceId: webapp-service
    webapp-connect:
      path: /connect**
      stripPrefix: false
      serviceId: webapp-service

    webapp-index:
      path: /index.html
      stripPrefix: false
      serviceId: webapp-service
    webapp-favicon:
      path: /favicon.ico
      stripPrefix: false
      serviceId: webapp-service
    webapp-api-js:
      path: /api/riots-api.js
      stripPrefix: false
      serviceId: webapp-service
    webapp-img:
      path: /img/**
      stripPrefix: false
      serviceId: webapp-service
    webapp-views:
      path: /views/**
      stripPrefix: false
      serviceId: webapp-service
    webapp-styles:
      path: /styles/**
      stripPrefix: false
      serviceId: webapp-service
    webapp-scripts:
      path: /scripts/**
      stripPrefix: false
      serviceId: webapp-service
    webapp-config:
      path: /config**
      stripPrefix: false
      serviceId: webapp-service
    webapp-root:
      path: /
      stripPrefix: false
      serviceId: webapp-service
    webapp-demo:
      path: /demo/**
      stripPrefix: false
      serviceId: webapp-service
    webapp-golfcars:
      path: /golfcar**
      stripPrefix: false
      serviceId: webapp-service

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/v2/
    

ribbon:
  ServerListRefreshInterval: 5000
  
spring:
  application:
    name: gateway-service

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF
    com.netflix.servo: WARN
    org.springframework: WARN
    org.springframework.cloud.netflix.zuul: INFO
