server:
  port: 8087

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/v2/

spring:
  application:
    name: docs-service

logging:
  level:
    com.netflix.discovery: OFF
    org.apache.cxf.interceptor: OFF

---
spring:
  profiles: eureka-embedded

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/
