server:
  port: 8088

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/

spring:
  application:
    name: docs-service

logging:
  level:
    com.netflix.discovery: OFF
    org.apache.cxf.interceptor: OFF
