kind: ReplicationController
apiVersion: v1beta2
id: redis
labels:
  name: redis
desiredState:
  replicas: 1
  replicaSelector:
    name: redis
  podTemplate:
    labels:
      name: redis
    desiredState:
      manifest:
        version: v1beta2
        id: redis
        containers:
          - name: redis
            image: redis:3.0.0
            ports:
              - containerPort: 6379
