server:
  port: 8083

elasticsearch:
  hostname: localhost

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/

ribbon:
  ServerListRefreshInterval: 5000

spring:
  application:
    name: catalog-service
    
logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF
    org.apache.cxf.interceptor: OFF
