server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/v2/

spring:
  application:
    name: catalog-service
    
logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF