server:
  port: 8083

elasticsearch:
  hostname: localhost

eureka:
  hostname: localhost
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/v2/

ribbon:
  ServerListRefreshInterval: 5000

spring:
  application:
    name: catalog-service
    
logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.zuul: OFF

---
spring:
  profiles: eureka-embedded

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:10000/eureka/
