package com.viotualize.api.services;

import com.viotualize.api.handlers.command.ManufacturerCommand;
import com.viotualize.api.handlers.query.ManufacturerQuery;
import com.viotualize.api.handlers.query.Paged;
import com.viotualize.core.domain.Manufacturer;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriBuilder;

/**
 * @author omoser
 */
@Service
@Path("/manufacturers")
@Api(value = "Manufacturers", description = "CRUD operations for Manufacturers")
public class Manufacturers {

    @Autowired
    ManufacturerQuery manufacturerQuery;
    
        @Autowired
        ManufacturerCommand ManufacturerCommand;
    
        @GET
        @Path("/{id}")
        @Produces(MediaType.APPLICATION_JSON)
        @ApiOperation(value = "Retrieve single Manufacturer",
                notes = "Retrieve Manufacturer by its ID. Manufacturer IDs are auto-generated by the API and cannot be modified",
                response = Manufacturer.class)
        @ApiResponses(value = {@ApiResponse(code = 404, message = "No Manufacturer with given ID found")})
        public Response retrieve(@PathParam("id") String ManufacturerId) {
            return Response.ok(manufacturerQuery.single(ManufacturerId)).build();
        }
    
        @GET
        @Path("/")
        @Produces(MediaType.APPLICATION_JSON)
        @ApiOperation(value = "Retrieve all Manufacturers",
                notes = "Retrieve all Manufacturers including their children",
                response = Manufacturer.class)
        @ApiResponses(value = {
                @ApiResponse(code = 404, message = "No Manufacturer with given ID found"),
                @ApiResponse(code = 400, message = "Either the query string or the paging parameters are malformed")
        })
        public Response list(@QueryParam("q") String query, @QueryParam("page") int page, @QueryParam("size") int size) {
            return Response.ok(manufacturerQuery.query(query, new Paged(page, size))).build();
        }
    
        @POST
        @Path("/")
        @Consumes({MediaType.APPLICATION_JSON})
        @Produces({MediaType.APPLICATION_JSON})
        @ApiOperation(value = "Created a new Manufacturer",
                notes = "Create a new Manufacturer according to the provided JSON payload. Manufacturer IDs are auto-assigned " +
                        "by the API and cannot be controlled. Please note that referenced Manufacturers have to exist prior " +
                        "to persisting a Manufacturer.Upon successful creation, HTTP 201 and a Location header for the" +
                        " created Manufacturer is returned."
        )
        @ApiResponses(value = {
                @ApiResponse(code = 400, message = "Malformed Manufacturer provided. See error message for details")
        })
        public Response create(Manufacturer Manufacturer) {
            Manufacturer = ManufacturerCommand.create(Manufacturer);
            return Response.created(UriBuilder.fromMethod(Manufacturers.class, "retrieve").build(Manufacturer.getId())).build();
        }
    
        @PUT
        @Path("/")
        @Consumes({MediaType.APPLICATION_JSON})
        @Produces({MediaType.APPLICATION_JSON})
        @ApiOperation(value = "Update an existing Manufacturer",
                notes = "Update an existing Manufacturer according to the provided JSON payload. Upon success, HTTP 200 is returned."
        )
        @ApiResponses(value = {
                @ApiResponse(code = 400, message = "Malformed Manufacturer provided. See error message for details")
        })
        public Response update(Manufacturer Manufacturer) {
            ManufacturerCommand.update(Manufacturer);
            return Response.ok().build();
        }
    
        @DELETE
        @Path("/{id}")
        @Produces({MediaType.APPLICATION_JSON})
        @ApiOperation(value = "Delete a Manufacturer",
                notes = "Delete an existing Manufacturer by its ID. Upon success, HTTP 200 is returned."
        )
        @ApiResponses(value = {
                @ApiResponse(code = 404, message = "No such Manufacturer")
        })
        public Response delete(@PathParam("id") String ManufacturerId) {
            ManufacturerCommand.delete(ManufacturerId);
            return Response.ok().build();
        }

}
